language: node_js
node_js:
  - "4"
  - "6"
  - "7"
  - node
script:
  - npm run check:src
  - npm run build
  - npm run test
  - npm run build:examples
branches:
  except:
    - experimental
cache:
  directories:
  - $HOME/.npm
  - examples/browser-basic/node_modules
  - examples/nodejs-basic/node_modules
